### ISSUE TITLE
Reasoning

### ISSUE THREAD

**Issue by oori** [cansik/webcam-capture-processing#2]
Hi

I understand this is experiment, not supported, not for production.  cool.  But still - I'd be happy to know from you what's the **reasoning** for this lib?  (beyond "simpler").
I've been a long time user of Sarxos's library, for the good and the bad.

Thanks!

**Comment by cansik** [comment]
The idea was to have another webcam-capture library besides processing-video (gstreamer based and about 700 MB on MacOS), which is way smaller and does just the things it's intended to do. Here are the two comments about this in the p5-discourse:

- [processing-cant-find-the-camera-video-libraries-dont-work/25128/16](https://discourse.processing.org/t/processing-cant-find-the-camera-video-libraries-dont-work/25128/16?u=cansik)
- [processing-cant-find-the-camera-video-libraries-dont-work/25128/18](https://discourse.processing.org/t/processing-cant-find-the-camera-video-libraries-dont-work/25128/18?u=cansik)

**Comment by oori** [comment]
thanks for the clarification
